### PR TITLE
small graph improvements

### PR DESCRIPTION
**Pull request by 3nids**
image

### CODE REVIEW

**Comment by olivierdalang** [comment]
Ok yes nice to also represent volumes.

I think something's wrong in the code though because how is it possible that there's a non-0 volume when there's 0 sections ? (didn't check the code, if you're using the aggregation maybe it's wrong there)

**Comment by 3nids** [comment]
image

most of the sections have 0 volumes.
I did not check yet further if it's an import error or an issue in the raw data.

**Comment by 3nids** [comment]
just checked the raw data, most of the volumes are null.

**Comment by 3nids** [comment]
see https://github.com/opengisch/sylvis/blob/master/scripts/pg2fixtures.sh#L52

**Review by olivierdalang — APPROVED** [review]
Ah ok I misread the graph, thought the bars were the counts and the line the volume...

Anyway ok for me the point at this stage is mostly to show we can do graphs !

**Pull request merged**
